apiVersion: skaffold/v2beta7
kind: Config
build:
  artifacts:
    - image: leeroy-web
      context: leeroy-web
    - image: leeroy-app
      context: leeroy-app
    - image: priyanka-php-apache
      context: priyanka-php-apche
  googleCloudBuild:
    projectId: searce-playground-v1
deploy:
  kubectl:
    manifests:
      - leeroy-web/kubernetes/*
      - leeroy-app/kubernetes/*
  helm:
    releases:
      - name: skaffold-helm
        chartPath: priyanka-php-apache/kubernetes
portForward:
  - resourceType: deployment
    resourceName: leeroy-web
    port: 8080
    localPort: 9000