steps:
  - name: gcr.io/k8s-skaffold/skaffold
    args:
      - skaffold
      - build
      - '--interactive=false'
      - '--default-repo=gcr.io/searce-playground-v1/priyanka-pipeline'
      # - '--file-output=artifacts.json'
    dir: example
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args: 
      - '-c'
      - >
        gcloud deploy releases create $(date +%y%m%d-%s)
        --delivery-pipeline=web-app 
        --source=./
        --region=us-central1
    dir: example
    entrypoint: bash 