apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: prod
description: prod cluster
requireApproval: true
gkeCluster:
  project: searce-playground-v1
  cluster: prod
  location: us-central1